version: '2'
services:
  testjhmongo-app:
    image: testjhmongo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://testjhmongo-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=testJhMongo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8088:8088
  testjhmongo-mongodb:
    extends:
      file: mongodb.yml
      service: testjhmongo-mongodb
